#!/bin/bash
container_id=$(docker run -dit ubuntu:latest)
container_ip_addr=$(docker container inspect -f '{{ .NetworkSettings.IPAddress }}' $container_id)
container_port=$(echo $container_port | cut -d'/' -f 1)
echo "Container id :: $container_id"
echo "IP address :: $container_ip_addr"
echo "Container Port :: $container_port"
